# it is CRITICAL that the keys specified here match the fixtures
tomcat:
  label: Tomcat
  description: Tomcat Application Server
  singleton: false
  props:
   - key: cargo.remote.username
     tooltip: Please enter the user name for logging on to the Tomcat Server
     label: User Name
     order_idx: 0
   - key: cargo.remote.password
     tooltip: Enter the password for logging on to the Tomcat Server
     label: Password
     type: password
     order_idx: 1
   - key: cargo.tomcat.manager.url
     tooltip: Enter the URL and port for the Tomcat Manager (e.g. http://vadev.mantech.com:4848/manager)
     label: Tomcat Manager URL
     type: url
     order_idx: 2
nexus:
  label: Nexus
  description: Nexus Artifactory Server
  singleton: true
  props:
   - key: nexus_repository_url
     tooltip: Enter the Nexus Repository URL for the Nexus Artifactory Server (e.g. http://vadev.mantech.com:8081/nexus/content/groups/everything/)
     label: Nexus Repository URL (Read)
     type: url
     order_idx: 0
   - key: nexus_publication_url
     tooltip: Enter the Nexus Repository URL for publishing to the Nexus Artifactory Server (e.g. http://vadev.mantech.com:8081/nexus/content/repositories/termdata/)
     label: Nexus Repository URL (Publish)
     type: url
     order_idx: 1
   - key: nexus_user
     tooltip: Enter the user name to use for logging on to the Nexus Server
     label: User Name
     order_idx: 2
   - key: nexus_pwd
     tooltip: Enter the password to use for logging on to the Nexus Server
     label: Password
     type: password
     order_idx: 3

jenkins:
  label: Jenkins
  description: Jenkins CI Server
  singleton: true
  props:
   - key: jenkins_root
     tooltip: Enter the URL address and port for the Jenkins Server (e.g. http://server_path:port)
     label: Root URL:port
     type: url
     order_idx: 0
   - key: jenkins_user
     tooltip: Enter the user name for logging onto the Jenkins Server
     label: User Name
     order_idx: 1
   - key: jenkins_pwd
     tooltip: Enter the password for logging onto the Jenkins Server
     label: Password
     type: password
     order_idx: 2

git:
  label: Git
  description: Git Repository
  singleton: true
  props:
   - key: git_repository_url
     tooltip: Enter the URL address and port for the Git Server (e.g. http://server_path:port) 
     label: Git Repository URL:port
     type: url
     order_idx: 0
   - key: git_user
     tooltip: Enter the git user name for logging on to the Git Server
     label: User Name
     order_idx: 1
   - key: git_pwd
     tooltip: Enter the git password for logging on to the Git Server
     label: Password
     type: password
     order_idx: 2

   # java.lang.System.getProperties.put('cargo.remote.username','devtest')
   # java.lang.System.getProperties.put('cargo.remote.password','devtest')
   # java.lang.System.getProperties.put('cargo.tomcat.manager.url','http://vadev.mantech.com:4848/manager')
   # java.lang.System.getProperties.put('cargo.servlet.port','4848')
   # java.lang.System.getProperties.put('cargo.hostname','vadev.mantech.com')

   #Nexus
   # nexus_root = http://vadev.mantech.com:8081/
   # nexus_user = devtest
   # nexus_pwd = devtest
