# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383a1e89e7dbd49c5cc49317473871031f67ae93ab528c8db02e3ed5b2c25b868a81950e8aabe02cfd2901380052865fd40e3aa3bb1598575aab7b2cc6e75c90

test:
  secret_key_base: c0568c73d04298caa8a70232856f47ddc34cef3f1ad1b8ba72041cf3d9fdfe1e949f42eeddada57311082f5532c36bdfb527806ce19f12d58cddeaa04f9c1bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
#to_do create rake task that generates this and appends to the end of the file.  Have maven call during build.
production:
  secret_key_base: 05c0c765c71bd6b55282b4c4ba6b9110e9713603e95c6ebb9c26765f7c87733a9059a6606cfde7ef54314514848fe9a17709f03a1c742f2d0ec01de3baf44b07
