application_urls:
  ssoi_logout: https://logon.dev2.iam.va.gov/centrallogin/centrallanding.aspx

proxy_config_root:
  apache_url_proxy: https://vaauscttweb81.aac.va.gov/
  proxy_urls:
    - incoming_url_path: https://vaauscttdbs81.aac.va.gov:8443/nexus #this is like our incoming url
      proxy_location: /nexus
    - incoming_url_path: https://vauscttweb81.aac.va.gov:8080/login #this is like our incoming url
      proxy_location: /jenkins
    - incoming_url_path: https://vaauscttdbs80.aac.va.gov:8080/rails_prisme/ #this is like our incoming url
      proxy_location: /prisme/
    - incoming_url_path: https://vaauscttweb80.aac.va.gov:8080/rails_komet_a/ #this is like our incoming url
      proxy_location: /komet/
    - incoming_url_path: https://vaauscttweb80.aac.va.gov:8080/manager/ #We play with this one
      proxy_location: /manager
    - incoming_url_path: https://vaauscttdbs80.aac.va.gov:8080/git/ #this is like our incoming url
      proxy_location: /git/
    - incoming_url_path: https://vaausappctt204.aac.va.gov:8080/isaac-rest-1
      proxy_location: /isaac-rest-1
    - incoming_url_path: https://vaausappctt204.aac.va.gov:8080/isaac-rest-2
      proxy_location: /isaac-rest-2
    - incoming_url_path: https://vaausappctt205.aac.va.gov:8080/isaac-rest-3
      proxy_location: /isaac-rest-3
    - incoming_url_path: https://vaausappctt205.aac.va.gov:8080/isaac-rest-4
      proxy_location: /isaac-rest-4
    - incoming_url_path: https://vaausappctt205.aac.va.gov:8080/komet_a
      proxy_location: /1/komet_a
    - incoming_url_path: http://localhost:3001/isaac-rest-billy_goat-local
      proxy_location: /2/isaac-rest
    - incoming_url_path: https://vadev.mantech.com:4848/isaac-rest-billy_goat
      proxy_location: /1/isaac-rest
    - incoming_url_path: https://vadev.mantech.com:4848/isaac-rest-freddy_cat
      proxy_location: /2/isaac-rest
    - incoming_url_path: http://localhost:3001/isaac-rest-freddy_cat-local
      proxy_location: /3/isaac-rest
    - incoming_url_path: http://localhost:3001/rails_komet_a
      proxy_location: /3/rails_komet_a
    - incoming_url_path: http://localhost:3001/rails_komet_b
      proxy_location: /3/rails_komet_b