#Note: the keys in the second level hash (listener_port, but not DEV) are converted into get methods dynamically.  The keys need to match the java interface
#gov.vha.isaac.ochre.services.dto.publish.ApplicationProperties
# note: interface_engine_URL is a special case.  ApplicationProperties has the method
# getInterfaceEngineURL, so take care with the case.
---
DEV_BOX:
  sending_facility_namespace_id: 200ET1
  ets_server: vaauscttdbs80.aac.va.gov
  interface_engine_URL: http://vaaacvies64.aac.dva.va.gov:8080/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49991
  hl7_encoding_type: VB
  use_interface_engine: false #set this to false for devbox
  response_listener_timeout: 0 #in minutes
DEV:
  sending_facility_namespace_id: 200ET1
  ets_server: vaauscttdbs80.aac.va.gov
  interface_engine_URL: http://vaaacvies64.aac.dva.va.gov:8080/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
  use_interface_engine: true
  response_listener_timeout: 15 #in minutes
TEST:
  sending_facility_namespace_id: 200ET10
  ets_server: vaauscttdbs82.aac.va.gov
  interface_engine_URL: http://vaaacvies64.aac.dva.va.gov:8080/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
  use_interface_engine: true
  response_listener_timeout: 15 #in minutes
INTEGRATION:
  sending_facility_namespace_id: 200ET20
  ets_server: vaausdbsctt700.aac.va.gov
  interface_engine_URL: http://vaaacvies64.aac.dva.va.gov:8080/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
  use_interface_engine: true
  response_listener_timeout: 15 #in minutes
PRE-PROD:
  sending_facility_namespace_id: 200ET30
  ets_server: vaausdbsctt402.aac.va.gov
  interface_engine_URL: http://vaaacviep44.aac.dva.va.gov:8080/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
  use_interface_engine: true
  response_listener_timeout: 15 #in minutes
PROD:
  sending_facility_namespace_id: 200ETS
  ets_server: vaausdbsctt202.aac.va.gov
  interface_engine_URL: http://vaaacviev24.aac.dva.va.gov:8080/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
  use_interface_engine: true
  response_listener_timeout: 15 #in minutes