---
DEV_BOX:
  ets_application_id: 200ET1
  ets_server: vaauscttdbs80.aac.va.gov
  interface_engine_url: http://vaaacvies64.aac.dva.va.gov:8090/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
DEV:
  ets_application_id: 200ET1
  ets_server: vaauscttdbs80.aac.va.gov
  interface_engine_url: http://vaaacvies64.aac.dva.va.gov:8090/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
INTEGRATION:
  ets_application_id: 200ET10
  ets_server: vaauscttdbs82.aac.va.gov
  interface_engine_url: http://vaaacvies64.aac.dva.va.gov:8090/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
SQA:
  ets_application_id: 200ET20
  ets_server: vaausdbsctt700.aac.va.gov
  interface_engine_url: http://vaaacvies64.aac.dva.va.gov:8090/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
PRE-PROD:
  ets_application_id: 200ET30
  ets_server: vaausdbsctt402.aac.va.gov
  interface_engine_url: http://vaaacviep44.aac.dva.va.gov:8090/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB
PROD:
  ets_application_id: 200ETS
  ets_server: vaausdbsctt202.aac.va.gov
  interface_engine_url: http://vaaacviev24.aac.dva.va.gov:8090/FrameworkClient-1.1/Framework2ServletHTTPtoChannel
  listener_port: 49990
  hl7_encoding_type: VB